# Generated by Django 4.1.10 on 2023-07-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='person-icon.png', upload_to='Profile_Image', verbose_name=''),
        ),
    ]
